### ISSUE TITLE
Temp on heater set to max, and boil turned off?

### ISSUE THREAD

**Issue by skalltje** [frodeheg/no.sparegris#165] opened 2023-01-14 09:13 UTC
Hi.
Using Homey, Tibber, Pulse, Sparegris, Sensibo for older heat pump and Heavy Duty Smart Switch.
Flow for current power is set.
But when using price management, temp on heat pump is set to 30 degree, and Heavy Duty Smart Switch is turned off?
I had to turn off the price management when temp in home is Sauna-mode 😬

**Comment by frodeheg** [comment] 2023-01-14 13:25
Hi, not exactly sure what you're asking for so I will give you two answers.

Piggy strives to keep all devices that have been set to be controllable / on to be powered on all the time. When this is not possible within the power budget you have set, then devices will start powering off, but they will be powered on again when you have sufficient power in the power budget.

So, if the problem is that the Heavy Duty Smart Switch turns off it is only that you use too much power within the power budget you selected, and you can increase this limit if you want, but then you won't save on the power-tariff.

On the other hand, if the problem is that the House is being heated more than you like, then you have to adjust the delta-temperatures on price point "grisebillig" or "cheap" so that the heat pump does not increase temperature as much. This is all controllable...

**Comment by frodeheg** [comment] 2023-01-16 23:06
Closing this ticket as it seems like the app has been incorrectly configured. Please let me know if you need help adjusting the settings to your preferences.

**Closed by frodeheg** 2023-01-16 23:06 UTC
Labels: invalid
