### ISSUE TITLE
Bug in automatic price point calculation 

### ISSUE THREAD

**Issue by slasktrat** [frodeheg/no.sparegris#55] opened 2022-10-30 09:19 UTC
I've enabled automatic price point calculation with default settings, but noticed that the app has set price point to expensive for the current hour, even though current price is below today's average.

![Screenshot_2022-10-30-10-05-33-13_7ea78f8a473b1abdf2a2d64da2436ec8](https://user-images.githubusercontent.com/11269880/198871278-45ee6591-be46-4002-9733-2b09ba3c3909.jpg)
![Screenshot_2022-10-30-10-05-45-30_4bbfc4a7dd885a2bb189f300112a7ed4](https://user-images.githubusercontent.com/11269880/198871288-4c40b489-c994-49e6-b370-2f47141dd066.jpg)

**Comment by frodeheg** [comment] 2022-10-31 19:47
Thanks for the report, I will look into it after I have fixed #57

**Comment by frodeheg** [comment] 2022-11-01 02:03
I cannot reproduce this under normal circumstances if I use the prices for that particular day with default settings.
However, I can envision 2 situations it can happen in, was any of these true?
* You had rebooted Homey within the last 15 minutes
* You had used some other price setting before where the price point was set to high. Then you changed the price settings in Piggy and saved. After this you could observe the high price point high was kept as long as the hour lapsed.

**Comment by frodeheg** [comment] 2022-11-06 03:29
So, I did a code review and discovered that the price region is not used when fetching spot prices.
those using prices externally (strømregning) are not affected, but the internal control apparently always fetched prices from NO3 (Trøndelag).

I am pretty sure this is the cause of your strange behaviour.
```
async function entsoeGetData(startTime, currency = 'NOK') {
  const biddingZone = '10YNO-3--------J';
```
This should be fixed asap.

**Comment by frodeheg** [comment] 2022-11-06 05:09
The fix has now been tested localy and seems to be working.
It has been pushed to testing in version 0.18.31.

**Closed by frodeheg** 2022-11-06 05:09 UTC
Labels: bug, critical, High priority
